name: Consecutive Workflow Action
description: Make workflow runs run consecutively.
branding:
  icon: fast-forward
  color: gray-dark
inputs:
  token:
    description: An access token to read information about workflows. (secrets.GITHUB_TOKEN)
    required: true
  interval:
    description: The interval in which to check for a status update
    required: false
    default: 10
runs:
  using: node12
  main: dist/index.js
