name: Demo
on:
  push:
    branches: [ main ]

jobs:
  # only run this workflow if the previous run has completed
  ready:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        workflow-id: demo.yml
        token: ${{ secrets.GITHUB_TOKEN }}

  # some other job
  something:
    runs-on: ubuntu-latest
    needs: [ ready ]
    steps:
    - run: echo "Previous workflow runs have completed!"