name: Unit Tests
on:
  push:
    branches: [ main ]

jobs:
  # only run this workflow if the previous one has completed
  ready:
    runs-on: ubuntu-latest
    steps:
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  # unit tests
  units:
    runs-on: ubuntu-latest
    needs: [ ready ]
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test